### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by bpabel** [westernx/sgschema#1]
This instance method appears to be referencing an undefined variable (in some cases it might exist globally, but that doesn't make sense on an instance method).

https://github.com/westernx/sgschema/blob/master/sgschema/schema.py#L196

Should this be `self` instead of `schema`?

**Comment by mikeboers** [comment]
Yes it should. :smile:

**Comment by bpabel** [comment]
Somewhat unrelated, but do you have any examples of a package that defines a schema via an entry point?

**Comment by mikeboers** [comment]
Sure thing. I just created/pushed an example of our `shotgun_api3_registry` package to https://github.com/westernx/shotgun_api3_registry which implements entry points for defining the schema, and loading a cached version.

**Comment by bpabel** [comment]
Cool, thanks.
